workflow:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^(master|smoke|^coverity-tested\/.*|stable-.*)$/
      when: never
    - when: always

stages:
  - analyze
  - build
  - test

include:
  - 'automation/gitlab-ci/analyze.yaml'
  - 'automation/gitlab-ci/build.yaml'
  - 'automation/gitlab-ci/test.yaml'
